version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/dmytrocharoian/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge