version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge